# -*- coding: utf-8 -*-
"""Face Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DpDR-pQa79sLNtH1RzUz5-Tnustsbz8S
"""

import cv2 as cv
from google.colab.patches import cv2_imshow
img = cv.imread('/content/drive/MyDrive/OpenCV/Photos/group 1.jpg')

gray=cv.cvtColor(img,cv.COLOR_BGR2GRAY)

haar_cascade=cv.CascadeClassifier('/content/haar_face.xml')

faces_rect=haar_cascade.detectMultiScale(gray,scaleFactor=1.1,minNeighbors=1)

print(f'Number of faces found = {len(faces_rect)}')

for (x,y,w,h) in faces_rect:
  cv.rectangle(img,(x,y),(x+w,y+h),(0,255,0),thickness=2)

cv2_imshow(img)